### ISSUE TITLE
Fork please?

### ISSUE THREAD

**Issue by xxv** [shinobisoft/android_kernel_lge_msm8226#1]
Thanks for releasing your changes! It's a bit hard to navigate what you've changed, though. Could you possibly fork the repo instead of re-importing it? That'd save you some trouble if you wanted to upgrade later to a newer kernel, too.

**Comment by shinobisoft** [comment]
You've lost me... Fork my own repo?... If you are referring to my other repository with the same name, that's a completely different kernel which I'm currently attempting to build for testing as it has been patched to version 3.4.105.

**Comment by xxv** [comment]
I meant https://github.com/Quarx2k/android_kernel_lge_msm8226 which this is stately based off of.

**Comment by shinobisoft** [comment]
Yes it is. However, if you've been following these devices you would also know that there are some diffrences between the D415 and the international models. The differences are not interchangeable. Meaning that the D415 requires a different kernel than the other variants... My project started off of Quarx project but it was necessary to NOT implement my changes to his kernel sources as it would screw up his builds and vice-versa.

**Comment by xxv** [comment]
OK. I guess the main thing is: how can I extract your changes such that I could, say, upgrade the kernel? Could you at least start off with the unchanged kernel and then apply your changes as a separate commit? I am planning on doing something like that, but you know what you changed much better than I'll be able to figure out :smile:

**Comment by shinobisoft** [comment]
Sorry, I had a long day yesterday and I'm kinda stubborn, LOL. Most of my changes are in the kernel configs as well as in device/lge/w7/BoardConfig.mk. The script that is used by the build system to create the boot image has also been modified which involved modifications to a couple of the kernel make files in - arch/arm/boot/dts, arch/arm/mach_msm, arch/arm/mach_msm/lge. Also, there were missing folders and files for the D415 variant in several of the aforementioned folders. They were aquired from LG's V10C sources. Quarx had hard coded the msm8226-w7ds_open_cis.dts files in one of the make files I mentioned as well. That code was removed and is handled by the modified mkbootimg.mk script from the device tree folder.
As much as I hate to say it, it's very possible that I've made other changes, but I'm drawing a blank as to what they may be at the moment. Sorry.

**Comment by xxv** [comment]
@shinobisoft I'm going to try to recreate the diff of what you changed. What exactly did you start with? Do you know the specific commit that you copied and started working on? If I can get that, then I can create a patch of the changes that you made from that.

**Comment by toxinburn** [comment]
Hey if you look up my github toxinburn i think i shoud still have a fork of
the original.

**Comment by xxv** [comment]
@toxinburn I'm trying to see what's different between @shinobisoft 's c32ae0d09421a5d96b8ef5406139bfe45b4616e5 commit (which lost all the history) and whatever he originally imported from. I'm guessing it's some commit somewhere in https://github.com/Quarx2k/android_device_lg_w7ds (maybe just https://github.com/Quarx2k/android_device_lg_w7ds/commit/d74ffebd0f4154c5c7ae4848cdc6ebb2cb4a8d53 )

**Comment by xxv** [comment]
@toxinburn I'm trying to find the difference between @shinobisoft 's c32ae0d09421a5d96b8ef5406139bfe45b4616e5 and some commit in https://github.com/Quarx2k/android_kernel_lge_msm8226/commits/cm-11.0 .

**Comment by xxv** [comment]
A quick script seems to indicate that the closest match is https://github.com/Quarx2k/android_kernel_lge_msm8226/commit/e9ddbabe15394df5735d70438142ec1dc7e998ea

**Comment by toxinburn** [comment]
Hey I am sorry to write here I am sorta newbish to messing with github but I got a major problem 20.3 and latest apk are making my stock moto camera 2 say it is busy and wll not work at all it just crashes only solution is to unroot so far the camera itself does not even show under magisk hide it was stock with phone I also noticed that you only have like one thing hidden by default under google now, anyway if you got any idea I could try I am on RETUS  XT1955-5 Moto G7 Power on latest firmware I do not recall this being a prob on the firmware prior but it is now, perhaps to messs wth us for rooting, i dont know but i have uninstalled it cleared caches, tried everything disabled tried other cam apps none will work at all. as long as I have magisk installed. I moved magisk to sd card to hoping maybe it would work but no dice, so far nothin I can do :( any help would be awesome thanks you have been a legend shinobisoft. I am just one user but if you find time I would love to try some things out to get it to work.

**Comment by shinobisoft** [comment]
@toxinburn I'm afraid I won't be much help. I've forgotten most of what I learned about ROM building long ago. I haven't been active in Android development in a few years. I just haven't had the time. What programming I still do is PC based. Sorry...

_Sent from my LG Stylo3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
